name: dart_switch
description: A little dart library for wrapping big "if - if else" blocks in a Switch..Case structure.
version: 0.1.0
author: Benjamin Jesuiter <bjesuiter@gmail.com>
homepage: https://plus.google.com/+BenjaminJesuiter/about/

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
